import { useState, useEffect } from 'react';
import axios from 'axios';
import { Pill, Calendar, User, FileText, Download, Printer, Building2 } from 'lucide-react';
import Sidebar from '../components/Sidebar';
import { useAuth } from '../context/AuthContext';

export default function Prescriptions() {
  const { user } = useAuth();
  const [prescriptions, setPrescriptions] = useState([]);
  const [loading, setLoading]  = useState(true);
  const [selected, setSelected] = useState(null);
  const [msg, setMsg]           = useState('');

  useEffect(() => {
    axios.get('/prescriptions/patient/all')
      .then(({ data }) => { setPrescriptions(data); setLoading(false); })
      .catch(() => setLoading(false));
  }, []);

  const print = (rx) => {
    const win = window.open('', '_blank');
    win.document.write(`<html><head><title>Prescription ${rx.ticketNumber}</title>
    <style>body{font-family:Arial,sans-serif;padding:30px;max-width:700px;margin:0 auto}
    h1{color:#1e3a8a;border-bottom:2px solid #1e3a8a;padding-bottom:8px}
    table{width:100%;border-collapse:collapse;margin-top:16px}
    th{background:#1e3a8a;color:#fff;padding:10px;text-align:left}
    td{padding:8px 10px;border:1px solid #e5e7eb}tr:nth-child(even){background:#f9fafb}
    .info{background:#f0f9ff;padding:14px;border-radius:8px;margin-bottom:16px}
    .footer{margin-top:40px;border-top:1px solid #e5e7eb;padding-top:12px;font-size:12px;color:#9ca3af;text-align:center}
    </style></head><body>
    <h1>MediQueueAI — Prescription</h1>
    <div class="info">
      <p><b>Patient:</b> ${rx.doctor?.name ? user?.name : '—'}</p>
      <p><b>Doctor:</b> Dr. ${rx.doctor?.name}</p>
      <p><b>Specialization:</b> ${rx.doctor?.specialization}</p>
      <p><b>Date:</b> ${rx.date}</p>
      <p><b>Ticket:</b> ${rx.ticketNumber}</p>
      <p><b>Diagnosis:</b> ${rx.prescription?.diagnosis || '—'}</p>
    </div>
    ${rx.prescription?.medicines?.length > 0 ? `
    <h3>Medicines Prescribed</h3>
    <table><thead><tr><th>Medicine</th><th>Dosage</th><th>Duration</th><th>Notes</th></tr></thead>
    <tbody>${rx.prescription.medicines.map(m=>`<tr><td><b>${m.name}</b></td><td>${m.dosage}</td><td>${m.duration}</td><td>${m.notes||'—'}</td></tr>`).join('')}
    </tbody></table>` : ''}
    ${rx.prescription?.instructions ? `<p style="margin-top:16px"><b>Instructions:</b> ${rx.prescription.instructions}</p>` : ''}
    ${rx.prescription?.followUpDate ? `<p><b>Follow-up Date:</b> ${rx.prescription.followUpDate}</p>` : ''}
    <div class="footer">Generated by MediQueueAI Hospital System • ${new Date().toLocaleDateString()}</div>
    </body></html>`);
    win.document.close();
    win.print();
  };

  return (
    <div className="main-layout">
      <Sidebar/>
      <div className="main-content">
        <div className="page-header">
          <h1 style={{ display:'flex', alignItems:'center', gap:'10px' }}><Pill size={24}/> My Prescriptions</h1>
          <p>All prescriptions from your consultations</p>
        </div>

        {loading ? <div className="loading"><div className="spinner"/></div> :
          prescriptions.length === 0 ? (
            <div className="card" style={{ textAlign:'center', padding:'48px', color:'#9ca3af' }}>
              <FileText size={48} style={{ marginBottom:'12px', opacity:.3 }}/>
              <div style={{ fontWeight:600 }}>No prescriptions yet</div>
              <div style={{ fontSize:'13px', marginTop:'4px' }}>Prescriptions from completed consultations will appear here</div>
            </div>
          ) : (
            <div style={{ display:'grid', gap:'14px' }}>
              {prescriptions.map(rx => (
                <div key={rx._id} className="card" style={{ borderLeft:'4px solid #3b82f6' }}>
                  <div style={{ display:'flex', justifyContent:'space-between', alignItems:'flex-start', flexWrap:'wrap', gap:'12px' }}>
                    <div style={{ flex:1 }}>
                      <div style={{ display:'flex', gap:'8px', alignItems:'center', marginBottom:'8px', flexWrap:'wrap' }}>
                        <span style={{ fontFamily:'monospace', fontSize:'11px', background:'#f1f5f9', padding:'2px 8px', borderRadius:'4px' }}>{rx.ticketNumber}</span>
                        <span className="badge badge-completed">Prescription Issued</span>
                      </div>
                      <div style={{ fontWeight:700, fontSize:'15px' }}>Dr. {rx.doctor?.name}</div>
                      <div style={{ color:'#3b82f6', fontSize:'12px', fontWeight:600 }}>{rx.doctor?.specialization}</div>
                      <div style={{ fontSize:'12px', color:'#6b7280', marginTop:'4px' }}>
                        <Calendar size={12}/> {rx.date}
                      </div>
                      {rx.prescription?.diagnosis && (
                        <div style={{ marginTop:'8px', padding:'8px 12px', background:'#f0f9ff', borderRadius:'8px', fontSize:'13px' }}>
                          <strong>Diagnosis:</strong> {rx.prescription.diagnosis}
                        </div>
                      )}
                      {rx.prescription?.medicines?.length > 0 && (
                        <div style={{ marginTop:'6px', display:'flex', gap:'6px', flexWrap:'wrap' }}>
                          {rx.prescription.medicines.map((m,i) => (
                            <span key={i} style={{ background:'#f5f3ff', color:'#5b21b6', padding:'3px 9px', borderRadius:'20px', fontSize:'11px', fontWeight:600 }}>
                              <Pill size={14} style={{ marginRight:'6px', color:'#ec4899' }}/> {m.name}
                            </span>
                          ))}
                        </div>
                      )}
                    </div>
                    <div style={{ display:'flex', gap:'7px' }}>
                      <button onClick={() => setSelected(selected?._id===rx._id ? null : rx)} className="btn btn-outline btn-sm">
                        <FileText size={13}/> Details
                      </button>
                      <button onClick={() => print(rx)} className="btn btn-primary btn-sm">
                        <Download size={13}/> Print
                      </button>
                    </div>
                  </div>

                  {/* Expanded prescription details */}
                  {selected?._id === rx._id && rx.prescription && (
                    <div style={{ marginTop:'16px', borderTop:'1px solid #e2e8f0', paddingTop:'16px' }}>
                      {rx.prescription.medicines?.length > 0 && (
                        <div style={{ marginBottom:'14px' }}>
                          <h4 style={{ fontWeight:700, marginBottom:'10px', fontSize:'14px', display:'flex', alignItems:'center', gap:'6px' }}><Pill size={14}/> Medicines</h4>
                          <div className="table-wrap">
                            <table>
                              <thead><tr><th>Medicine</th><th>Dosage</th><th>Duration</th><th>Notes</th></tr></thead>
                              <tbody>
                                {rx.prescription.medicines.map((m,i) => (
                                  <tr key={i}>
                                    <td style={{ fontWeight:600 }}>{m.name}</td>
                                    <td>{m.dosage}</td>
                                    <td>{m.duration}</td>
                                    <td style={{ color:'#6b7280', fontSize:'12px' }}>{m.notes||'—'}</td>
                                  </tr>
                                ))}
                              </tbody>
                            </table>
                          </div>
                        </div>
                      )}
                      {rx.prescription.instructions && (
                        <div style={{ padding:'10px 14px', background:'#f0fdf4', borderRadius:'8px', fontSize:'13px', marginBottom:'10px' }}>
                          <strong>Instructions:</strong> {rx.prescription.instructions}
                        </div>
                      )}
                      {rx.prescription.followUpDate && (
                        <div style={{ padding:'10px 14px', background:'#eff6ff', borderRadius:'8px', fontSize:'13px' }}>
                          <Calendar size={14}/> <strong>Follow-up:</strong> {rx.prescription.followUpDate}
                          {rx.prescription.followUpNotes && ` — ${rx.prescription.followUpNotes}`}
                        </div>
                      )}
                    </div>
                  )}
                </div>
              ))}
            </div>
          )}
      </div>
    </div>
  );
}
